server:
  port: 8007
spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hello?characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
      # 下面为连接池的补充设置 ，应用到上面所有的数据源中
      # 初始化大小，最大，最小
      initial-size: 5
      min-idle: 5
      max-wait: 50
      # 配置间隔多久才能进行一次检查，检查需要关闭的连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小的生存单位，单位是毫秒
      min-evictable-idle-time-millis: 30000
  quartz:
    #持久化到数据库方式
    job-store-type: jdbc
    initialize-schema: embedded
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
mybatis:
  type-aliases-package: cn.com.nanfeng.junittest.model.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true