server:
  port: 9002
spring:
  application:
    name: security-gateway
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    root: info
    org:
      springframework: info
zuul:
  retryable: true
  ignored-services: "*"
  add-host-header: true
  sensitive-headers: "*"
  routes:
    uaa:
      path: /uaa/**
      service-id: UAA-SERVICE
    order:
      path: /order/**
      service-id: ORDER-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: [text/xml,application/xml,application/json]

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
