server:
  port: 8096
spring:
  application:
    name: @artifactId@
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hello?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      #初始化大小、最大、最小
      initial-size: 10
      min-idle: 10
      max-wait: 100
      #配置间隔多久才进行一次检测，检测需要关闭的连接，单位为毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小的生存单位，单位为毫秒
      min-evictable-idle-time-millis: 30000
  redis:
    #配置默认数据库
    database: 1
    #服务器地址
    host: 192.168.147.129
    #端口号
    port: 6379
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #连接池最大阻塞等待时间
        max-wait: -1
        #连接池最大空闲连接
        max-idle: 8
        #连接池最小空闲连接
        min-idle: 0
    timeout: 300
mybatis:
  type-aliases-package: cn.com.nanfeng.simpletest.model.po
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true