server:
  port: 9527
spring:
  redis:
    database: 0
    host: 192.168.147.132
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 控制一个pool最多有多少个状态为idle(空闲的)的jedis实例
        max-idle: 100
        # 控制一个pool最少有多少个状态为idle(空闲的)的jedis实例
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
      shutdown-timeout: 10000
    timeout: 10000
    sentinel:
      master: mymaster
      nodes: 192.168.147.132:26379,192.168.147.132:26389,192.168.147.132:26399
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hello?characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
      #初始化 最大 最小
      initial-size: 5
      min-idle: 5
      max-wait: 50
      #配置间隔多久才进行一次检查，检查需要关闭的连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接池中的最小的生存单位，单位毫秒
      min-evictable-idle-time-millis: 30000
mybatis:
  type-aliases-package: cn.com.nanfeng.boot.model.po
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true