server:
  port: 9527
spring:
  redis:
    database: 0
    host: 192.168.147.132
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 控制一个pool最多有多少个状态为idle(空闲的)的jedis实例
        max-idle: 100
        # 控制一个pool最少有多少个状态为idle(空闲的)的jedis实例
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
      shutdown-timeout: 10000
    timeout: 10000
    sentinel:
      master: mymaster
      nodes: 192.168.147.132:26379,192.168.147.132:26389,192.168.147.132:26399