server:
  port: 8006
spring:
  redis:
    database: 0
    password: nanfengbujing123
    cluster:
      max-redirects: 3 #获取失败最大重定向次数
      nodes:
        - 192.168.147.132:7000
        - 192.168.147.132:7001
        - 192.168.147.132:7002
        - 192.168.147.132:7003
        - 192.168.147.132:7004
        - 192.168.147.132:7005
    lettuce:
      shutdown-timeout: 10000
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 #连接池中最大空闲连接数
        min-idle: 0 #连接池中的最小空闲连接
        max-wait: -1 #连接池最大阻塞等待时间（-1表示没有负值）

  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hello?characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
      #初始化 最大 最小
      initial-size: 5
      min-idle: 5
      max-wait: 50
      #配置间隔多久才进行一次检查，检查需要关闭的连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接池中的最小的生存单位，单位毫秒
      min-evictable-idle-time-millis: 30000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
